# Generated by Django 5.2.11 on 2026-02-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('observed', 'Dólar Observado'), ('customs', 'Dólar Aduanero')], max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('rate_type', 'date')},
            },
        ),
    ]
