# Generated by Django 5.2.11 on 2026-02-15 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fob_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('freight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cif', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ad_valorem', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
