# Generated by Django 5.2.11 on 2026-02-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_importsimulation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importsimulation',
            old_name='cif',
            new_name='cif_clp',
        ),
        migrations.AddField(
            model_name='importsimulation',
            name='cif_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
