# Generated by Django 5.2.11 on 2026-02-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course_lesson_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
