# Generated by Django 5.2.11 on 2026-02-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprogress_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
    ]
