# Generated by Django 5.2.11 on 2026-02-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprogress_avatar_userprogress_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='bio',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
    ]
