# Generated by Django 5.2.11 on 2026-02-18 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_professionalprofile_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Conectados'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='networking.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, help_text='Universidad o Instituto', max_length=200)),
                ('career', models.CharField(blank=True, help_text='Ej: Téc. en Comex, Ingeniería en Logística', max_length=200)),
                ('study_level', models.CharField(choices=[('1', '1er Año / Semestre 1-2'), ('2', '2do Año / Semestre 3-4'), ('3', '3er Año / Semestre 5-6'), ('4', '4to Año / Semestre 7-8'), ('egresado', 'Egresado / Titulado'), ('practica', 'En Práctica Profesional')], default='1', max_length=20)),
                ('area_interest', models.CharField(choices=[('comex', 'Comercio Exterior'), ('logistica', 'Logística y Transporte'), ('ambas', 'Ambas')], default='comex', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Breve presentación para tus compañeros')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfessionalProfile',
        ),
    ]
